# Generated by Django 2.2.3 on 2022-05-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220422_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
