# Generated by Django 2.2.3 on 2022-05-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_placedorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlacedOrders',
            new_name='PlacedOrder',
        ),
    ]
